### ISSUE TITLE
Varying probability of affiliation of leaf nodes under same parent

### ISSUE THREAD

**Issue by dsubhaji** [dsubhaji/NW-synthesis#4]
## Look at the console output below. What is going wrong after choice 3?

Choose(Press 1 or 2):
1.Network Growth Model
2.Network Connection Model
2
Select the parameter which you want to vary over a range of values:
1.No of branches
2.Height
3.Probability of affiliation of leaf nodes under same parent
4.Given level?
5.Probability of affiliation at a given level
6.Random affiliation probability
3
dirName= <something>

You have selected Probability of affiliation
Enter lower limit:
0.1

Enter upper limit:
0.9

You have selected Given Level
Enter lower limit:
0.1
Exception in thread "main" java.lang.NumberFormatException: For input string: "0.1"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Integer.parseInt(Unknown Source)
    at java.lang.Integer.<init>(Unknown Source)
    at net.dattas.nwsynthesis.control.NetworkModelingController.manualRun(NetworkModelingController.java:181)
    at select.main(select.java:33)

**Comment by dsubhaji** [comment]
Thanks!
